name: Build and Push Container Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      # Define your environment variables here
      MY_ENV_VAR: 'value'
      ANOTHER_ENV_VAR: 'another_value'

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Podman
      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      # Step 3: Log in to Quay.io
      - name: Log in to Quay.io
        run: |
          echo ${{ secrets.QUAY_PASSWORD }} | podman login quay.io --username ${{ secrets.QUAY_USERNAME }} --password-stdin

      # Step 4: Build and push the container image to Quay.io
      - name: Build and push Container image
        run: |
          podman build -t quay.io/rbrhssa/reports-api:latest -f Containerfile .
          podman push quay.io/rbrhssa/reports-api:latest

      # Step 5: Verify the image pushed successfully (optional)
      - name: Verify image exists in Quay.io
        run: |
          echo "Verifying the image has been pushed successfully to Quay.io..."
          podman pull quay.io/rbrhssa/reports-api:latest
