# .github/workflows/build-and-push.yml
name: Build and Push to Quay.io

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Quay.io
        run: |
          echo "${{ secrets.QUAY_IO_PASSWORD }}" | docker login quay.io -u "${{ secrets.QUAY_IO_USERNAME }}" --password-stdin

      - name: Build and push to Quay.io
        run: |
          docker build -t quay.io/rbrhssa/reports-api:latest .
          docker push quay.io/rbrhssa/reports-api:latest
